version: "3"
services:
    osrm:
        container_name: osrm
        image: osrm/osrm-backend
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - .:/data
        command: "osrm-routed --max-table-size=300 --algorithm mld /data/brandenburg.osm.pbf"
        networks:
            tsp_network:
                aliases:
                - osrm
    vroom-backend:
        container_name: vroom-backend
        image: iedmrc/vroom
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - osrm
        networks:
            tsp_network:
                aliases:
                - vroom-backend
    vroom-frontend:
        container_name: vroom-frontend
        image: iedmrc/vroom-frontend
        restart: always
        ports:
            - "9966:9966"
        depends_on:
            - osrm
            - vroom-backend
        networks:
            tsp_network:
                aliases:
                - vroom-frontend
networks:
  tsp_network:
      driver: bridge